"""add telegram_id

Revision ID: 3f6dfd953706
Revises: 4e32ce13fa8b
Create Date: 2025-08-11 17:07:34.280438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6dfd953706'
down_revision: Union[str, Sequence[str], None] = '4e32ce13fa8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_user_telegram_id', ['telegram_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
